// Generated by CoffeeScript 1.6.3
(function() {
  this.showGoalStats = function(id) {
    return $("div#single-goal-stats-div").fadeOut(function() {
      return $("div#loading").fadeIn(function() {
        var url;
        url = Routing.generate("b_conway_tracker_goal_view_stats", {
          id: id
        });
        return $.get(url, function(html) {
          var e;
          try {
            if (html.indexOf("login_form") > -1) {
              return window.location = window.location;
            } else {
              $("div#single-goal-stats-div").html(html);
              return $("div#loading").fadeOut(function() {
                return $("div#single-goal-stats-div").fadeIn();
              });
            }
          } catch (_error) {
            e = _error;
            return alert("Error loading goal stats");
          }
        }).fail(function() {
          alert("Error loading goal stats");
          return $("div#loading").fadeOut(function() {
            return $("div#single-goal-stats-div").fadeIn();
          });
        });
      });
    });
  };

  this.displayGoalStats = function(stats) {
    var headerStyles;
    if (stats && (stats != null)) {
      headerStyles = {
        cursor: "pointer",
        height: "25px"
      };
      $("div#single-goal-header").text("Goal: " + stats.goalWeight + " lbs by " + stats.endDate).css(headerStyles);
      $("div#single-goal-header").attr("onclick", "");
      $("div#single-goal-header").attr("onclick", "showGoalList();");
      if (stats.lastWeighInWeight) {
        $("span#single-goal_recent-weighin_weight").text(stats.lastWeighInWeight.toString());
      }
      if (stats.estimatedCurrentWeight) {
        $("span#single-goal_calculated-current-weight").text(stats.estimatedCurrentWeight.toString());
      }
      if (stats.relativeWeighinsCount) {
        $("span#single-goal_relative-weighins").text(stats.relativeWeighinsCount.toString());
      }
      if (stats.goalLength && stats.goalDaysRemaining) {
        $("span#single-goal_days-remaining").text(stats.goalDaysRemaining.toString() + "/" + stats.goalLength.toString());
      }
      if (stats.currentCalorieDeficit) {
        $("span#single-goal_current-calorie-deficit").text(stats.currentCalorieDeficit.toString());
      }
      if (stats.totalCaloriesToLoseRemaining) {
        $("span#single-goal_total-deficit-remaining").text(stats.totalCaloriesToLoseRemaining.toString());
      }
      if (stats.totalAverageDeficitNeeded) {
        $("span#single-goal_total-average-deficit-needed").text(stats.totalAverageDeficitNeeded.toString());
      }
      if (stats.currentAverageDeficitNeeded) {
        $("span#single-goal_average-deficit-needed").text(stats.currentAverageDeficitNeeded.toString());
      }
      if (stats.currentAverageDeficit) {
        $("span#single-goal_average-deficit").text(stats.currentAverageDeficit.toString());
      }
      if (stats.deficitProgress) {
        $("div#single-goal_progress-text").text(stats.deficitProgress.toString() + "%");
        $("div#single-goal_progress-bar_bar").css({
          width: stats.deficitProgress.toString() + "px"
        });
      }
      if (stats.startWeight) {
        $("span#single-goal_start-weight").text(stats.startWeight.toString());
      }
      if (stats.goalWeight) {
        $("span#single-goal_end-weight").text(stats.goalWeight.toString());
      }
      if (stats.startDate) {
        $("span#single-goal_start-date").text(stats.startDate.toString());
      }
      if (stats.endDate) {
        $("span#single-goal_end-date").text(stats.endDate.toString());
      }
      if (stats.deficitSinceLastWeighin) {
        return $("span#single-goal_most-recent-weighin-calorie-deficit").text(stats.deficitSinceLastWeighin.toString());
      }
    }
  };

  this.showGoalSettings = function(id) {
    var url;
    url = Routing.generate("b_conway_tracker_goal_edit", {
      id: id
    });
    return $("div#edit_goal").fadeOut(function() {
      return $("div#loading").fadeIn(function() {
        return $.get(url, function(html) {
          var e;
          try {
            $("div#edit_goal").html(html);
            $("div#loading").fadeOut(function() {
              return $("div#edit_goal").fadeIn();
            });
            return $("input.date_picker").datepicker({
              dateFormat: "yy-mm-dd"
            });
          } catch (_error) {
            e = _error;
            return alert("Error loading goal settings");
          }
        }).fail(function() {
          return alert("Error loading goal settings");
        });
      });
    });
  };

  this.createNewGoal = function() {
    var url;
    url = Routing.generate("b_conway_tracker_goal_create");
    return $("div#edit_goal").fadeOut(function() {
      return $("div#loading").fadeIn(function() {
        return $.get(url, function(html) {
          var e;
          try {
            $("div#edit_goal").html(html);
            $("div#loading").fadeOut(function() {
              return $("div#edit_goal").fadeIn();
            });
            return $("input.date_picker").datepicker({
              dateFormat: "yy-mm-dd"
            });
          } catch (_error) {
            e = _error;
            return alert("Error creating new goal");
          }
        }).fail(function() {
          return alert("Error creating new goal");
        });
      });
    });
  };

}).call(this);
