parameters:
#    b_conway_user.example.class: BConway\UserBundle\Example

services:
#    b_conway_user.example:
#        class: %b_conway_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bconway_user.profile.form.type:
        class: BConway\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bconway_user_profile}

    bconway_user.profile.password_resetting:
            class: BConway\UserBundle\EventListener\PasswordResettingListener
            arguments: [ @router ]
            tags:
                - { name: kernel.event_subscriber }